version: '3'

services:
  docker-mysql:
    image: mysql:8.0.26
    volumes:
      - ./deploy:/tmp
    command: mysqld --init-file="/tmp/payroll-ddl.sql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=fonyou
      - MYSQL_PASSWORD=fonyou
    ports:
      - 3307:3306

  app:
    build: ./core
    ports:
       - 8091:8091
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/database?autoReconnect=true&useSSL=false
    depends_on:
       - docker-mysql
