version: '3'

services:
  mysqldb:
    image: mysql:8.0.26
    container_name: mysqldb
    hostname: mysqldb
    volumes:
      - "./deploy:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fonyou
      - MYSQL_USER=fonyou
      - MYSQL_PASSWORD=fonyou
    ports:
      - 3307:3306

  app:
    build: ./core
    container_name: app
    ports:
       - 8091:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/fonyou
    command: sh -c './wait-for-it.sh mysqldb:3306 --timeout=0 && catalina.sh run'
    depends_on:
       - mysqldb
